### ISSUE TITLE
[POLL] automatic babelization/typescript compilation of makfyfile.js

### ISSUE THREAD

**Issue by xaviergonz** [xaviergonz/makfy#1]
Since right now async/await is only supported by node 7.6+, would it be interesting if makfy automatically babelized (if the file ends in .es6) and/or compiled using typescript (if the file ends in .ts) the makfyfile at runtime?

Or should we just assume node 8 will soon come and leave it up to users to babelize/typescript compile the file if they are using node 6.

Alternatively, using typescript could be cool since the whole thing already uses typescript and could export its types to make sure the makfyfile.ts file is well formed without having to run the program...

Thoughts?

**Comment by wmertens** [comment]
How about adding a `-r <module>` flag like node has? That way `makfy -r babel-register` would auto-transpile, without needing to add special code to makfy.

Another way, which Webpack uses, is to use https://www.npmjs.com/package/interpret which requires the correct interpreter based on the extension. So then `makfyfile.babel.js` would be auto-transpiled.

**Comment by xaviergonz** [comment]
@wmertens thanks for the tips :) I'll take a look and get back

**Comment by xaviergonz** [comment]
closed since from v1.3.0 makfy supports .ts files out of the box
