### ISSUE TITLE
Cannot use two setEnvVars in one exec

### ISSUE THREAD

**Issue by wmertens** [xaviergonz/makfy#3]
when I run 

```js
			await exec(
				util.setEnvVar('NODE_ENV', 'development'),
				args.inspect ? util.setEnvVar('DEBUG_SERVER', 'true') : null,
				// TODO find a wp plugin that clears the output dir before writing
				`rimraf ${buildPath}`,
				`webpack --config ${wpConfPath} --watch --color`
			)
```

with the `--inspect` arg given, I get the error `[ERROR] only one command can be run at the same time`. Without `--inspect` it works fine.

**Comment by wmertens** [comment]
perhaps `setEnvVar` should also accept a map so that multiple keys can be passed in one go?

**Comment by wmertens** [comment]
argh PEBKAC error - I was running `makfy start -- --inspect` instead of `makfy start --inspect`. Sorry for the noise.

**Comment by xaviergonz** [comment]
happens to me often, it is hard to break old habits :D
