### ISSUE TITLE
Commands undetected when running with global binary

### ISSUE THREAD

**Issue by SanderRonde** [xaviergonz/makfy#6]
When running `makfy` from the global binary, the list of commands will always be empty. I looked at the code and it appears the global `makfy` installation requires the local makfyfile.(js|ts), which in turn requires the local `makfy` installation. So the global `makfy` installation is never actually required by it and no commands are registered on it.

This might be fixable with something like intercepting `require` calls to the local makfy installation and re-routing them to whichever instance is handling the current CLI call. Or maybe even requiring the local makfy installation and copying its commands back to the global one.

**Comment by xaviergonz** [comment]
Thanks for the bug report!
This should be now fixed in v2.0.1, if not feel free to reopen the issue :)
