### ISSUE TITLE
Fails when `SHELL` environment variable is not defined

### ISSUE THREAD

**Issue by SanderRonde** [xaviergonz/makfy#9]
When using makfy in an environment where the `SHELL` environment variable is not defined, will exit with the error "[ERROR] The "file" argument must be of type string. Received undefined". This is because [on this line](https://github.com/xaviergonz/makfy/blob/dd14240e7d8bcd8800261611ed869385311b0277/src/lib/execRuntime.ts#L384) the assumption is made that `SHELL` is always defined. However, this is not defined in Github Actions containers.

I'd suggest falling back to `sh` if `process.env.SHELL` is not defined, since that seems to work fine at least in the github actions case.

FYI you can use [act](https://github.com/nektos/act) to create a local github actions container in case you want to experiment with it yourself.

**Comment by xaviergonz** [comment]
Thanks for the detailed bug report! should be fixed in 2.0.4

**Comment by SanderRonde** [comment]
Great, thanks!
